name: mypy_flake

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m venv ./venv
        source venv/bin/activate
        pip install -r requirements.txt
    - name: Analysing the code
      run: |
        pip install mypy
        python -m pip install types-emoji
        mypy --ignore-missing-imports $(git ls-files 'src/*.py')
        pip install flake8
        flake8  $(git ls-files 'src/*.py')
